PROGRAM Sunday
REAL RAND,UPPER_LIMIT,LOWER_LIMIT,SUM,CUR,TEMP
INTEGER COUNT
REAL, PARAMETER :: PI = 4 * DATAN(1.D0)
CALL RANDOM_NUMBER(RAND)
UPPER_LIMIT = 3*PI / 2
LOWER_LIMIT = PI
SUM = 0
DO I = 0,1000
  CALL RANDOM_NUMBER(RAND)
  TEMP = LOWER_LIMIT + (UPPER_LIMIT - LOWER_LIMIT) * RAND
  CUR = -COS(LOWER_LIMIT + (UPPER_LIMIT - LOWER_LIMIT) * RAND)
  SUM = SUM + CUR
  COUNT = COUNT + 1
  PRINT *,TEMP
END DO  
SUM = SUM / COUNT
PRINT *,"SUM: ", SUM , " COUNT: ",COUNT
END PROGRAM Sunday