PROGRAM Converter
REAL READER,FPART
INTEGER IPART,FPC,UL,N,NN,L,K,Q,W,P,CUR_FPART
INTEGER, PARAMETER :: B = 2
INTEGER, DIMENSION(0:50) :: INTEGER_PART
INTEGER, DIMENSION(0:50) :: FRACTIONAL_PART
OPEN(1, FILE = "A.txt")
!-READING
READ(1, *) READER 
CLOSE(1)
IPART = AINT(READER)
FPART = READER - AINT(READER)
INTEGER_PART = 0
FRACTIONAL_PART = 0
!____ FRAC PART TO BINARY
N = 0
W = 0
CUR_FPART = -1
FPART = FPART * 2
DO WHILE(N < 24 )
  IF(FPART >= 1 )THEN
    FPART = FPART - 1
    INTEGER_PART(N) = 1
  ELSE
    INTEGER_PART(N) = 0
  END IF
  FRACTIONAL_PART(W) = FPART
  FPART = FPART * 2
  W = W + 1
  N = N + 1 
  IF(ANY(FRACTIONAL_PART == FPART))THEN
    EXIT
  END IF
END DO 
NN = N
!Integer part to binary
DO WHILE (IPART >= 1)
  IF(MOD(IPART,B) == 1)THEN
    INTEGER_PART(N) = 1
  ELSE 
    INTEGER_PART(N) = 0
  END IF  
  IPART = IPART / 2
  N = N + 1
END DO
!____OUT
OPEN(1, FILE = "B.txt")
IF(NN == N)THEN
  N = N + 1
END IF
DO K = N - 1,NN ,-1
  L = INTEGER_PART(K)
  WRITE(1,*) L
  PRINT *,"-",L
END DO
PRINT *,"            ",",          -FRACTIONAL PART"
WRITE(1,*) ','
DO K = 0 ,NN - 1
  L = INTEGER_PART(K)
  PRINT *,"-",L
  WRITE(1,*) L
END DO
END PROGRAM Converter