PROGRAM Converter
INTEGER IPART,FPART,FPC,N,NN,L,K,Q,UL,W,P,CUR_FPART
INTEGER, PARAMETER :: B = 2
INTEGER, DIMENSION(0:50) :: INTEGER_PART
INTEGER, DIMENSION(0:50) :: FRACTIONAL_PART
OPEN(1, FILE = "A.txt")
READ(1, *) IPART,FPART ! IF HAS NO FRACTIONAL PART REMOVE FPART
INTEGER_PART = 0
FRACTIONAL_PART = 0
!_____ COUNT 
FPC = FPART
Q = 0
DO WHILE(FPC > 9)
  FPC = FPC / 10
  Q = Q + 1
END DO 
UL = 10 ** (Q + 1)
!____ FRAC PART TO BINARY
N = 0
W = 0
CUR_FPART = -1
FPART = FPART * 2
DO WHILE(N < 24 )
  IF(FPART > UL .OR. FPART == UL)THEN
    FPART = FPART - UL
    INTEGER_PART(N) = 1
  ELSE
    INTEGER_PART(N) = 0
  END IF
  FRACTIONAL_PART(W) = FPART
  FPART = FPART * 2
  W = W + 1
  N = N + 1 
  IF(ANY(FRACTIONAL_PART == FPART))THEN
    EXIT
  END IF
END DO 
NN = N
!Integer part to binary
DO WHILE (IPART >= 1)
  IF(MOD(IPART,B) == 1)THEN
    INTEGER_PART(N) = 1
  ELSE 
    INTEGER_PART(N) = 0
  END IF  
  IPART = IPART / 2
  N = N + 1
END DO
!____OUT
IF(NN == N)THEN
  N = N + 1
END IF
DO K = N - 1,NN ,-1
  L = INTEGER_PART(K)
  PRINT *,"-",L
END DO
PRINT *,"            ",",          -FRACTIONAL PART"
DO K = 0 ,NN - 1
  L = INTEGER_PART(K)
  PRINT *,"-",L
END DO
PRINT *,INTEGER_PART
END PROGRAM Converter