PROGRAM Converter !bad precision in frac part
REAL READER,FPART
INTEGER IPART,FPC,UL,N,NN,L,K,Q,W,P,CUR_FPART
INTEGER, PARAMETER :: B = 2
INTEGER, DIMENSION(0:50) :: IN_BINARY
REAL, DIMENSION(0:50) :: APPEARED
OPEN(1, FILE = "A.txt")
!-READING
READ(1, *) READER 
CLOSE(1)
IPART = AINT(READER)
FPART = READER - AINT(READER)
IN_BINARY = 0
APPEARED = 0
!____ FRAC PART TO BINARY
N = 0
W = 0
CUR_FPART = -1
FPART = FPART * 2
DO WHILE(N < 49 )
  IF(FPART >= 1 )THEN
    FPART = FPART - 1
    IN_BINARY(N) = 1
  ELSE
    IN_BINARY(N) = 0
  END IF
  APPEARED(W) = FPART
  FPART = FPART * 2
  W = W + 1
  N = N + 1 
  IF(ANY(APPEARED == FPART))THEN
    EXIT
  END IF
END DO 
NN = N
!Integer part to binary
DO WHILE (IPART >= 1)
  IF(MOD(IPART,B) == 1)THEN
    IN_BINARY(N) = 1
  ELSE 
    IN_BINARY(N) = 0
  END IF  
  IPART = IPART / 2
  N = N + 1
END DO
!____OUT
OPEN(1, FILE = "B.txt")
IF(NN == N)THEN
  N = N + 1
END IF
DO K = N - 1,NN ,-1
  L = IN_BINARY(K)
  WRITE(1,*) L
  PRINT *,"-",L
END DO
PRINT *,"            ",",          -FRACTIONAL PART"
WRITE(1,*) ','
DO K = 0 ,NN - 2
  L = IN_BINARY(K)
  PRINT *,"-",L
  WRITE(1,*) L
END DO
END PROGRAM Converter