PROGRAM Sunday ! -1
REAL RAND,UPPER_LIMIT,LOWER_LIMIT,SUM,CUR
REAL, PARAMETER :: PI = 4 * DATAN(1.D0)
CALL RANDOM_NUMBER(RAND)
UPPER_LIMIT = 3 * PI / 2
LOWER_LIMIT = PI
SUM = 0
COUNT = 0
DO I = 0,10000
  CALL RANDOM_NUMBER(RAND)
  CUR = -COS(LOWER_LIMIT + (UPPER_LIMIT - LOWER_LIMIT) * RAND)
  SUM = SUM + CUR
END DO  
SUM = SUM / (I + 1)
PRINT *,"SUM: ", SUM , " COUNT: ",I
END PROGRAM Sunday