PROGRAM QWE
REAL RAD,COS,DIVISOR,DIVIDEND,D_PART1,D_PART2,MON
INTEGER TEST
MON = -1
TEST = 2
COS = 0
RAD = 3.80785847 
DIVISOR = 0
DIVIDEND = 0
D_PART1 = 0
D_PART2 = 0
DO I = 0, 17
DIVISOR = FACT(2 * I)
PRINT *,"DIVS : " ,DIVISOR , " ITER: ", I
D_PART1 =  POW(MON,I)
PRINT *,"D_PART1: " ,D_PART1 , " ITER: ", I
D_PART2 = POW(RAD,2*I)
PRINT *,"D_PART2: " ,D_PART2 , " ITER: ", I
DIVIDEND = D_PART1 * D_PART2
COS = DIVIDEND / DIVISOR + COS
PRINT *,"cos : " ,COS , " ITER: ", I
END DO
PRINT *,COS
CONTAINS
  FUNCTION FACT( N )
  INTEGER FACT, N, TEMP
  TEMP = 1
  DO J = 2, N
    TEMP = J * TEMP
  END DO
  FACT = TEMP
  END FUNCTION

  
  FUNCTION POW(X,K)
  REAL X,TEMPOR
  INTEGER K
  TEMPOR = X
  DO M = 2,K
    TEMPOR = TEMPOR * TEMPOR
  END DO
  POW = TEMPOR
  END FUNCTION
END PROGRAM QWE