PROGRAM Montecarlo
INTEGER NUMBER_OF_INTERVALS
REAL START,END,CUR,MC,RAND
REAL, PARAMETER :: PI = 4 * DATAN(1.D0)
NUMBER_OF_INTERVALS = 100
START = PI
END = 3 * PI / 2
MC = 0
DO I = 1,NUMBER_OF_INTERVALS
  CALL RANDOM_NUMBER(RAND)
  CUR = START + (END - START) * RAND
  MC = MC + SIN(CUR)
END DO
MC = (END - START) * MC / NUMBER_OF_INTERVALS
PRINT*,MC
END PROGRAM Montecarlo